apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - name: container-1
    image: nginx 
  - name: container-2
    image: busybox
    command:
     - sleep
     - "3600"