apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-first-container
    image: busybox
    command: ["echo"]
    args: ["Welcome to my world"]
# THIS IS ONBLY FOR DEMO
